openapi: 3.1.0
x-stoplight:
  id: lgqfsl425myax
info:
  title: app
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    parameters: []
    get:
      summary: ユーザー一覧取得API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  x-stoplight:
                    id: gflnmjypz6w6z
                  type: object
                  properties:
                    id:
                      type: number
                      x-stoplight:
                        id: 4glenl950x97x
                      description: id
                    username:
                      type: string
                      x-stoplight:
                        id: w5ul9uk3nh178
                      description: ユーザーネーム
                    password:
                      type: string
                      x-stoplight:
                        id: fmuzxc2lc3uys
                      description: パスワード
                  required:
                    - id
                    - username
                    - password
              examples: {}
      operationId: get-users-userId
      description: ユーザー一覧を取得するAPI
  /login:
    get:
      summary: アクセストークン発行API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    x-stoplight:
                      id: ol5xoxxw1e8rn
                    description: トークン
        '500':
          description: ''
          content: {}
      operationId: get-login
      description: アクセストークンを発行するAPI
  '/user/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    delete:
      summary: ユーザー情報削除API
      operationId: delete-user-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    x-stoplight:
                      id: x1sqxa46087cq
                    description: id
                  username:
                    type: string
                    x-stoplight:
                      id: 1ftmqnj35s6hf
                    description: username
                  password:
                    type: string
                    x-stoplight:
                      id: j49zlra6e5ynz
                    description: password
                required:
                  - id
                  - username
                  - password
        '400':
          description: ''
        '404':
          description: ''
      description: ユーザー情報を削除するAPI
  /user:
    post:
      summary: ユーザー情報登録API
      operationId: post-user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    x-stoplight:
                      id: 2pqvpdo9avlms
                  username:
                    type: string
                    x-stoplight:
                      id: 3j4ndaowvbf53
                  password:
                    type: string
                    x-stoplight:
                      id: wgpa28cvml38n
                required:
                  - id
                  - username
                  - password
        '400':
          description: ''
        '401':
          description: ''
        '500':
          description: ''
      description: ユーザー情報を登録するAPI
components:
  schemas: {}
